export const NavigationElementsFooter1 = [
  { id: "0", title: "About", url: "#" },
  { id: "1", title: "Blog", url: "#" },
  { id: "2", title: "Careers", url: "#" },
  { id: "3", title: "Press", url: "#" },
  { id: "4", title: "Contact", url: "#" },
];

export const NavigationElementsFooter2 = [
  { id: "0", title: "Register as Doctor", url: "/register_as_doctor" },
  { id: "1", title: "Help", url: "#" },
  { id: "2", title: "Developer", url: "#" },
  { id: "3", title: "Privacy Policy", url: "#" },
  { id: "4", title: "Terms & Conditions", url: "#" },
  { id: "5", title: "Doctor Profile", url: "/doctorProfile" },
  { id: "6", title: "Patient Profile", url: "/patientProfile" },
  //   { id: "4", title: "Contact", url: "#" },
];

export const NavigationElementsFooter3 = [
  { id: "0", title: "Facebook", url: "#" },
  { id: "1", title: "Instagram", url: "#" },
  { id: "2", title: "YouTube", url: "#" },
  { id: "3", title: "LinkedIn", url: "#" },
  //   { id: "4", title: "Contact", url: "#" },
];

export const JharkhandLocation = [
  { id: "0", city: "Garhwa", state: "Jharkhand" },
  { id: "1", city: "Palamu", state: "Jharkhand" },
  { id: "2", city: "Chatra", state: "Jharkhand" },
  { id: "3", city: "Hazaribagh", state: "Jharkhand" },
  { id: "4", city: "Koderma", state: "Jharkhand" },
  { id: "5", city: "Giridih", state: "Jharkhand" },
  { id: "6", city: "Deoghar", state: "Jharkhand" },
  { id: "7", city: "Dumka", state: "Jharkhand" },
  { id: "8", city: "Godda", state: "Jharkhand" },
  { id: "9", city: "Sahebganj", state: "Jharkhand" },
  { id: "10", city: "Pakur", state: "Jharkhand" },
  { id: "11", city: "Latehar", state: "Jharkhand" },
  { id: "12", city: "Ramgarh", state: "Jharkhand" },
  { id: "13", city: "Bokaro", state: "Jharkhand" },
  { id: "14", city: "Dhanbad", state: "Jharkhand" },
  { id: "15", city: "Jamtara", state: "Jharkhand" },
  { id: "16", city: "Lohardaga", state: "Jharkhand" },
  { id: "17", city: "Ranchi", state: "Jharkhand" },
  { id: "18", city: "Gumla", state: "Jharkhand" },
  { id: "19", city: "Khunti", state: "Jharkhand" },
  { id: "20", city: "Simdega", state: "Jharkhand" },
  { id: "21", city: "West Singhbhum", state: "Jharkhand" },
  { id: "22", city: "East Singhbhum", state: "Jharkhand" },
  { id: "23", city: "Jamshedpur", state: "Jharkhand" },
  // { id: "24", city: "", state: "Jharkhand" },
  // { id: "25", city: "", state: "Jharkhand" },
  // { id: "26", city: "", state: "Jharkhand" },
  // { id: "27", city: "", state: "Jharkhand" },
  // { id: "28", city: "", state: "Jharkhand" },
  // { id: "29", city: "", state: "Jharkhand" },
  // { id: "30", city: "", state: "Jharkhand" },
];